general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    path = ~/Pictures/wallpaper.jpg
    blur_passes = 2
    blur_size = 4
}

# --- time ---
label {
    text = cmd[update:1000] echo "Well what you want time.."
    color = rgba(235, 235, 235, 0.9)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = bottom
}

